# Site
name: "Duke Institute for Brain Sciences Methods Meetings"
title: "Duke Institute for Brain Sciences Methods Meetings"
description: "Workshops and tutorials on  methods, statistics, and models in neuroscience."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: 
include: ["_pages"]
permalink: /:title/
future: true

# Authors
authors:
  allie:
    name: Allie
    display_name: Allie Sinclair
    avatar: assets/images/Sinclair.jpeg
    gravatar:
    email: allie.sinclair@duke.edu
    web: https://alyssasinclair.com
    twitter: https://twitter.com/sinclair_allie
    description: "PhD Candidate in Cognitive Neuroscience at Duke University working with Dr. Alison Adcock and Dr. Gregory Samanez-Larkin studying how people learn from error."

  anne:
    name: Anne
    display_name: Anne Draelos
    avatar: assets/images/anne.jpg
    gravatar:
    email: amw73@duke.edu
    web: https://draelos.github.io
    twitter: https://twitter.com/annedraelos
    description: "Postdoc in Biostats & Neuroscience at Duke University working with Dr. John Pearson on real-time adaptive experimental methods."

  ari:
    name: Ari
    display_name: Ari Khoudary
    avatar: assets/images/ari.jpeg
    gravatar:
    email: ari.khoudary@uci.edu
    web: https://arikhoudary.com
    twitter: https://twitter.com/ari_khoudary
    description: "PhD Student in Cognitive Science at UC Irvine working with Dr. Megan Peters and Dr. Aaron Bornstein on memory, perception, and metacognition."

  audrey:
    name: Audrey
    display_name: Audrey Siqi-Liu
    avatar: assets/images/audrey.png
    gravatar:
    email: audrey.liu@duke.edu
    web: 
    twitter: 
    description: "Post-defense PhD in Cognitive Neuroscience at Duke University working with Tobias Egner and Marty Woldorff studying adaptive cognitive flexibility."

  daniela:
    name: Daniela
    display_name: Daniela DeAlbuquerque
    avatar: assets/images/daniela.jpg
    gravatar:
    email: dfd4@duke.edu
    web: 
    twitter: 
    description: "MD-PhD Student in Electrical and Computer Engineering at Duke University working with Dr. John Pearson on statistical methods for neuroscience."

  ding:
    name: Ding
    display_name: Yaohui Ding
    avatar: 
    email: yd169@duke.edu
    gravatar:
    web:
    twitter:
    description:

  gabriela:
    name: Gabriela
    display_name: Gabriela Fernandez Miranda
    avatar: assets/images/gabriela.jpg
    gravatar:
    email: gabriela.fernandez@duke.edu
    web: https://gabrielafernandezmiranda.github.io
    twitter: https://twitter.com/GabrielaFM12
    description: "PhD Student at Duke University working with Dr. Felipe De Brigard."

  kevin:
    name: Kevin
    display_name: Kevin O'Neill
    avatar: assets/images/kevin.jpg
    gravatar:
    email: kevin.oneill@duke.edu
    web: https://kevingoneill.github.io
    twitter: https://twitter.com/kevingoneill
    description: "PhD Candidate in Cognitive Neuroscience at Duke University working with Dr. Felipe De Brigard and Dr. John Pearson on causal reasoning."

  liz:
    name: Liz
    display_name: Liz O'Gorman
    avatar: assets/images/liz.png
    gravatar:
    email: elizabeth.ogorman@duke.edu
    web: https://eaogorman.github.io/
    twitter: https://twitter.com/eaogorman
    description: "PhD Candidate in Neurobiology and MS Student in ECE at Duke University working with Dr. John Pearson on real-time adaptive experimental methods and deep learning."

  miles:
    name: Miles
    display_name: Miles Martinez
    avatar: assets/images/miles.jpg
    gravatar:
    email: miles.martinez@duke.edu
    web:
    twitter:
    description: "PhD Student in Cognitive Neuroscience at Duke University working with Dr. John Pearson on variational inference."

  nathan:
    name: Nathan
    display_name: Nathan Liang
    avatar: assets/images/nathan.jpg
    gravatar:
    email: nl453@cornell.edu
    web: https://1nathanliang.github.io
    twitter: https://twitter.com/1nathan_liang
    description: "PhD Student in Social & Personality Psychology at Cornell University working with Dr. Laura Niemi on social learning and moral reasoning."

  pranjal:
    name: Pranjal
    display_name: Pranjal Gupta
    avatar: assets/images/pranjal.jpg
    gravatar:
    email: pranjal.gupta@duke.edu
    web:
    twitter:
    description: "PhD Student in Cognitive Neuroscience at Duke University working with Dr. John Pearson on online dimensionality reduction."

  raphael:
    name: Raphael
    display_name: Raphael Geddert
    avatar: assets/images/raphael.jpg
    gravatar:
    email: raphael.geddert@duke.edu
    web:
    twitter: https://twitter.com/raphaelgeddert
    description: "PhD Candidate in Cognitive Neuroscience at Duke University working with Dr. Tobias Egner on cognitive control."

  shenyang:
    name: Shenyang
    display_name: Shenyang Huang
    avatar: assets/images/shenyang.jpg
    gravatar:
    email: shenyang.huang@duke.edu
    web: https://huang-shenyang.github.io/
    twitter: https://twitter.com/SelfShenyang
    description: "PhD Student in Cognitive Neuroscience at Duke University working with Dr. Roberto Cabeza, Dr. Simon Davis, and Dr. Felipe De Brigard."

  trevor:
    name: Trevor
    display_name: Trevor Alston
    avatar: assets/images/trevor.jpg
    gravatar:
    email: trevor.alston@duke.edu
    web:
    twitter:
    description: "PhD Student in Neurobiology at Duke University working with Dr. John Pearson on dimensionality reduction."


collections:
  personal_page:
    output: true

defaults:
  - scope:
      path: ""
      type: personal_page
    values:
      layout: personal_page
      permalink: people/:name

google_site_verification : google5d59576ff62047c3.html

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
#markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client:
adsense-data-ad-slot:

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, cache, _source, render]

theme: jekyll-theme-minimal
